services:
  db-ekstraPresensi:
    image: mysql:5.7
    container_name: smk-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ekstraDanPresensi
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: smk1ekstraDanPresensi
      MYSQL_PASSWORD: smkbisa
    
    command: --max_allowed_packet=4096M
    
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared
    restart: unless-stopped

volumes:
  db_data:

networks:
  shared:
    name: shared  
    
